<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="8.5.116" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="8.5.116" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Destination\" />
    <Folder Include="DTOs\Activity\" />
    <Folder Include="DTOs\Expense\" />
    <Folder Include="DTOs\Share\" />
    <Folder Include="DTOs\Trip\" />
    <Folder Include="Constants\" />
    <Folder Include="Exceptions\" />
  </ItemGroup>

</Project>
